### PR TITLE
Feats and fixes

### PR DESCRIPTION
**Pull request by abougouffa**
First, let me thank you for this package!

This PR fixes the `treesitter-context-fold-mode` and adds integration for `evil-mode`.

### Side question:
I'm wondering if it is possible to provide functions for folding/unfolding all blocks in the buffer? Something like `treesitter-context-fold-show-all` and `treesitter-context-fold-hide-all`. This will be extremely useful!

### CODE REVIEW

**Comment by zbelial** [comment]
Hi, thanks for your PR. Merged already. 

With regard to `treesitter-context-fold-show-all` and `treesitter-context-fold-hide-all`, can you give more details?  I'm not sure I understand what `all` here means. Thanks.

**Comment by zbelial** [comment]
I think for different languages, `all` means different things, right?  Maybe we can use some variable like `treesitter-context--java-fold-node-types-for-all` to specify what kinds of nodes should be considered as `all`?

**Comment by abougouffa** [comment]
> I think for different languages, `all` means different things, right? Maybe we can use some variable like `treesitter-context--java-fold-node-types-for-all` to specify what kinds of nodes should be considered as `all`?

Thank you for the reply @zbelial,

Well, in code-folding packages I've seen, `all` means all the **blocks inside the top level node**, so for example, in a file like this:

```python
import a, b, c

class A:
    def __init__(self):
        pass

class B:
    def __init__(self):
        pass

def func_a(x, y, z):
    if x == 0:
        if y == 2:
            return z
        else:
            return y
    else:
        return x

def func_b(x, y, z):
    pass
```

Fold all will fold it to:

```python
import a, b, c

class A:...

class B:...

def func_a(x, y, z):...

def func_b(x, y, z):...
```

**Comment by zbelial** [comment]
Thanks @abougouffa .  Absolutely it's doable, but I need more time to think about what should be folded and how to implement it. I'll ping you when it's finished.

**Comment by zbelial** [comment]
> Well, in code-folding packages I've seen, `all` means all the **blocks inside the top level node**

What code-folding packages have you used? I think I can learn something from them. Thanks.  

I have tried this feature of `yafolding` and `hideshow`,  yafolding worked well in rust and python buffers(haven't tested in other languages), but hideshow failed to hide all.

**Pull request merged**
